name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: "Build"
        run: |
          cd DisasterServer
          dotnet restore
          dotnet build --configuration Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: DisasterServer-Windows
          path: ${{ github.workspace }}\DisasterServer\bin\Release\net7.0\
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: "Build"
        run: |
          cd DisasterServer
          dotnet restore
          dotnet build --configuration Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: DisasterServer-Linux
          path: ${{ github.workspace }}/DisasterServer/bin/Release/net7.0/

